name: Bug 报告 / Bug Report
description: 提交 Bug 以帮助我们提高应用体验 / Submit a bug to help us improve the application experience
title: "[Bug] Title"
assignees: Richasy
labels:
  - "bug"
body:
- type: markdown
  attributes: 
    value: |
      ## 写在开头 / Beginning
      🚨 请务必完整填写下面的内容，如果缺少必要的信息，开发者可能会在未调查的情况下直接关闭问题 🚨  
      🚨 Be sure to fill out the following completely, if the necessary information is missing, the developer may close the issue without investigating 🚨
      
- type: textarea
  id: description
  validations:
    required: true
  attributes:
     label: Bug 描述 / Description
     description: 请简短的描述你遇到的问题 / Please briefly describe the issue you encountered
- type: textarea
  id: repro-steps
  validations:
    required: true
  attributes:
     label: 复现问题的步骤 / Steps to reproduce
     render: plain text
     description: 请提供复现问题的步骤，如果不能，请写明原因 / Please provide the steps to reproduce the issue, if not, please state the reason
     placeholder: |
        干净清晰的复现步骤有助于开发者更快定位问题所在，你所遇到的问题也会获得更高的优先级.  
        Clean and clear reproduction steps help developers locate the problem faster, and the issue you encounter will also get higher priority.
- type: textarea
  id: expected-behavior
  validations:
    required: true
  attributes:
     label: 预期行为 / Expected behavior
     description: 简要描述你希望看到什么样的结果 / Briefly describe what you would like to see
- type: textarea
  id: screenshots
  attributes:
     label: 截图 / Screenshots
     description: 如果可以，提交截图更有助于我们分析问题 / If possible, submitting screenshots will help us analyze the problem
- type: checkboxes
  id: environment-app-target-version
  attributes:
     label: 系统版本
     description: 选择一个你发现问题的系统版本
     options:
       - label: Windows 10 21H1 (Build 19043)
       - label: Windows 11 21H2 (Build 22000)
       - label: Windows 11 22H2 (Build 22621)
       - label: Windows 11 23H2 (Build 22631)
       - label: Windows 11 24H2 (Build 26100)
       - label: 其它 (需注明) / Other (Specify)
- type: input
  id: environment-app-target-other-version
  attributes:
     label: 其它系统版本 / Other system version
     description: 如果你是在特别的系统版本中运行应用，请注明系统版本 / If you are running the application in a special system version, please specify the system version
- type: dropdown
  id: form-factor
  attributes: 
     multiple: true
     label: 运行设备 / Running device
     description: 选择你当前运行小幻阅读的设备类型 / Select the type of device you are currently running the Rodel Reader on
     options:
       - 桌面（个人电脑） / Desktop (Personal Computer)
       - 桌面（平板或笔记本） / Desktop (Tablet or Laptop)
       - ARM64 设备 / ARM64 Device
- type: textarea
  id: log-info
  attributes:
     label: 日志记录 / Log
     description: |
      请在应用设置中打开 日志记录 面板，打开日志文件夹，选取问题发生当日的日志记录作为 Issue 的附件上传。  
      Open the Log panel in the application settings, open the log folder, select the log for the day the problem occurred as an attachment to the Issue.
- type: textarea
  id: additional-context
  attributes:
     label: 备注 / Additional context
     description: 添加你认为有必要的信息 / Add any additional context you think is necessary