name: 功能需求 / Feature Request
description: 给项目提供建议或点子 / Provide suggestions or ideas for the project
title: "[Feature] Title"
labels:
  - "enhancement"
assignees: Richasy
body:
- type: markdown
  attributes: 
    value: |
      ## 写在开头 / Beginning
      🚨 请务必完整填写下面的内容，如果缺少必要的信息，开发者可能会在未调查的情况下直接关闭问题 🚨  
      🚨 Be sure to fill out the following completely, if the necessary information is missing, the developer may close the issue without investigating 🚨

- type: textarea
  id: problem-description
  validations: 
    required: true
  attributes: 
    label: 功能描述 / Feature Description
    description: 描述你想要解决的问题或者功能的使用场景 / Describe the problem or use case for the feature you want to solve
    placeholder: |
      请描述你遇到的问题并介绍这个功能如何解决你的问题.  
      Please describe the problem you are experiencing and describe how this feature solves your problem.

- type: textarea
  id: alternatives
  attributes: 
    label: 备选方案 / Alternatives
    description: 问题的解决方法不止一种，也许你有一个退而求其次的方案 / There is more than one way to solve a problem, maybe you have a second best solution
    placeholder: |
      当你提到的功能难以实现时，你是否考虑了其他的替代方案？是否有一个最低的，可接受的实现目标？  
      When the current solution is difficult to implement, have you considered other alternatives? Is there a minimum, acceptable implementation goal?

- type: textarea
  id: additional-info
  attributes:
    label: 附加信息 / Additional Information
    description: |
      添加一些你认为有必要的备注信息，或者展示一些能表现你思路的草图
      Add some notes you think are necessary, or show some sketches that can show your ideas